name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      - name: Install Jest
        run: npm install jest
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test 
      - name: CodeThreat Scanner
      # You may pin to the exact commit or the version.
      # uses: CodeThreat/codethreat-github-action@972fb5cff9236c9e09944fa54022bc3ee56a0e61
        uses: CodeThreat/codethreat-github-action@v1.020
        with:
        # FAILED_ARGS
          FAILED_ARGS: |
                 - max_number_of_critical: 23
                 - max_number_of_high: 23
                 - weakness_is: ".*injection,buffer.over.read,mass.assigment"
                 - condition: 'OR'
                 - automerge: true
                 - sync_scan: true
                 - sca_max_number_of_critical: 23
                 - sca_max_number_of_high: 23
                 - policy_name: Advanced Security
          
