name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      - name: Install Jest
        run: npm install jest
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test 
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
        # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 11
          distribution: "Eclipse Temurin"
        # The package type (jdk, jre, jdk+fx, jre+fx)
          java-package: "jdk"
        # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true
        # ID of the distributionManagement repository in the pom.xml file. Default is `github`
          server-id: github
    # Path to where the settings.xml file will be written. Default is ~/.m2.
          settings-path: ~/.m2.
    # Overwrite the settings.xml file if it exists. Default is "true".
          overwrite-settings: true
    # Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".
          cache: "maven"
  
          
